language: go

go:
  - 1.10.x

services:
  - docker

before_install:
  - docker image build -t vinci7/hello_ci .
  - docker run -d -p 80:80 --name hello vinci7/hello_ci

script:
  - curl localhost:80

notifications:
  slack:
    rooms:
    - dragon-ball-zju:XX6hoGyynbzcsPHz6vZwVw4i#travis-ci
    on_success: always
    on_failure: always